spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://localhost:3306/htax_base?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
            username: root
            password: 403949009
#            driver-class-name: dm.jdbc.driver.DmDriver
#            url: jdbc:dm://localhost:5236?schema=WJZCGL&compatibleMode=mysql&characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asiz/Shanghai
#            username: WJZCGL
#            password: WJ123456789
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            #Oracle需要打开注释
            #validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                #login-username: admin
                #login-password: admin
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: false
                wall:
                    config:
                        multi-statement-allow: true


#多数据源的配置
#dynamic:
#  datasource:
#    slave1:
#      driver-class-name: dm.jdbc.driver.DmDriver
#      url: jdbc:dm://192.168.1.250:5236/ENSURE
      # mysql有longtext text blog等大数据库类型，迁移到达梦 一般会转换为clob类型，查询时会报类型转换异常，在url后面添加配置将clob当作string处理；
#      url: jdbc:dm://192.168.1.250:5236?schema=ENSURE&compatibleMode=mysql&characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asiz/Shanghai
#      username: ENSURE
#      password: EN123456789

#    slave2:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/htax_base?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#      username: root
#      password: root
elasticsearch:
    url: http://127.0.0.1:9200
